basic.forever(function () {
    basic.showNumber(5)
    basic.showNumber(6)
    basic.showNumber(7)
    basic.showNumber(8)
    basic.showIcon(IconNames.Heart)
    basic.pause(500)
    basic.showString("LOVE")
    basic.pause(100)
    basic.showString("YOU")
    basic.pause(1000)
    basic.showIcon(IconNames.Heart)
    basic.clearScreen()
})
